### PR TITLE
Add new proxy-type pool

### PR DESCRIPTION
**Pull request by rany2**
Pool and Luminati seem to be the only proxy-types that give residential IPs. I think peer doesn't do anything.

This also changes the behavior of peer to use country from `country_code.peer` to just `country_code`. It seems like I misunderstood what the extension does

### CODE REVIEW

**Comment by Snawoot** [comment]
Thanks!

**Comment by aarivex** [comment]
Can you describe this a bit further? It confuses me.

The `peer` type worked just fine for me, in 95% of the cases I got residential IPs. (Tested for US, UK and DE)
.. Well, at least I thought it did.
Yesterday the DE upstream strangely didn't work for a brief time, but it works again.

What confuses me the most is that whoer.net gives me a different IP than almost any other IP checkup website does.
I use FoxyProxy and hola-proxy runs on my server. When I use whoer to look up my IP address, it gives me an residential IP, whereas browserleaks and ip-api.com report completely different results.

Now I saw this update. Are the new lum/pool flags just a synonym for peer or does it actually do something different?

Nevertheless I'm glad I stumbled upon this project and I wish best of luck for the future as its a great tool and really helps me out a ton.

**Comment by rany2** [comment]
@aarivex 

> Okay, I figured out why whoer.net gave me different results than other pages. Any other website tells me the exact IP of the hola agent server thats being connected to, whereas whoer.net somehow figures out the IP that I "should've got" and displays me the residential IP instead. Weird. Should I open an issue about this?

This is only for `-proxy-type peer`? Right?

**Comment by aarivex** [comment]
> 
> 
> @aarivex
> 
> > Okay, I figured out why whoer.net gave me different results than other pages. Any other website tells me the exact IP of the hola agent server thats being connected to, whereas whoer.net somehow figures out the IP that I "should've got" and displays me the residential IP instead. Weird. Should I open an issue about this?
> 
> This is only for `-proxy-type peer`? Right?

Exactly. See https://github.com/Snawoot/hola-proxy/issues/13#issuecomment-792727205

**Comment by aarivex** [comment]
Alright, I just figured out that Hola and Luminati are "siblings". Luminati basically sells IPs mostly from Hola nodes.

This is probably why the new proxy type is called **lum**.
Does this access Luminati IPs though? Or is it just something like an alias?

I'd also like to mention that I still only get **Altus Communications** IPs when using lum or pool.
Is this intended? Can anyone reproduce? Else I'd open an issue for this.

**Comment by rany2** [comment]
Yes, this is intended. I've added the  proxy-types because they're used 
by the extension for different reasons (which I can't figure out). 
Hopefully someone figures it out by accident, but so far I'm using lum 
mostly

Altus Communications is returned by the extension too. its normal

**Pull request merged**
