### PR TITLE
Detect block

### LINKED ISSUE #24: Add way of detecting if API blocks you
```shell
$ curl -X POST --data-raw 'login=1&ver=1.181.350' \
         --user-agent \
         'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36'  \
         https://client.hola.org/client_cgi/background_init?uuid=`uuidgen | tr -d '-'`
{"blocked":true,"permanent":false}
```

could be used to detect if API blocks you. If it does, we might want to add the ability to login using Hola accounts as another workaround besides using a proxy

Edit: would be better than the cryptic: `CRITICAL Unable to determine proxy endpoint: No tunnels found in API response`

### PR DESCRIPTION
**Pull request by Snawoot**
Resolve #24

### CODE REVIEW

**Comment by rany2** [comment]
I've been blessed with a new block, I'll do a `git pull` and report back ;)

**Comment by rany2** [comment]
Never mind I got unbanned again... So I tried with tor as http_proxy, here are the results: 

```shell
$ eval http{,s}_proxy=socks5://$RANDOM:$RANDOM@127.0.0.1:9050 ./bin/hola-proxy 
MAIN    : 2021/03/12 21:59:07 main.go:101: INFO     Constructing fallback DNS upstream...
MAIN    : 2021/03/12 21:59:07 main.go:107: INFO     Initializing configuration provider...
CRED    : 2021/03/12 21:59:09 credservice.go:35: CRITICAL Configuration bootstrap failed: invalid character '<' looking for beginning of value
MAIN    : 2021/03/12 21:59:09 main.go:110: CRITICAL Unable to instantiate credential service: invalid character '<' looking for beginning of value
$ eval http{,s}_proxy=socks5://$RANDOM:$RANDOM@127.0.0.1:9050 ./bin/hola-proxy 
MAIN    : 2021/03/12 21:59:11 main.go:101: INFO     Constructing fallback DNS upstream...
MAIN    : 2021/03/12 21:59:11 main.go:107: INFO     Initializing configuration provider...
CRED    : 2021/03/12 21:59:12 credservice.go:35: CRITICAL Configuration bootstrap failed: temporary ban detected
MAIN    : 2021/03/12 21:59:12 main.go:110: CRITICAL Unable to instantiate credential service: temporary ban detected
```

the first `CRITICAL Unable to instantiate credential service: invalid character '<' looking for` is caused because hola-proxy is trying to parse hola-proxy's 403 forbidden error page: 
```html
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

```

second time worked fine

**Comment by Snawoot** [comment]
@rany2 when you receive `blocked` as a part of JSON response, which HTTP status code do you get? you can check it with `-D -` option for curl or even `-v` option.

**Comment by rany2** [comment]
@Snawoot 

```
$ torsocks -u $RANDOM -p $RANDOM curl -v -X POST --data-raw 'login=1&ver=1.181.350' --user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36' https://client.hola.org/client_cgi/background_init?uuid=`uuidgen | tr -d '-'`; echo
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 54.243.128.120:443...
* Connected to client.hola.org (54.243.128.120) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.hola.org
*  start date: May 26 00:00:00 2019 GMT
*  expire date: May 29 23:59:59 2021 GMT
*  subjectAltName: host "client.hola.org" matched cert's "*.hola.org"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55de4e1d3b20)
> POST /client_cgi/background_init?uuid=6fb0a5ae3f794a949101606ab9a317f4 HTTP/2
> Host: client.hola.org
> user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36
> accept: */*
> content-length: 21
> content-type: application/x-www-form-urlencoded
> 
* We are completely uploaded and fine
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< server: nginx
< date: Fri, 12 Mar 2021 20:07:09 GMT
< content-type: application/json; charset=utf-8
< content-length: 34
< vary: Origin, Accept-Encoding
< cache-control: private,no-store
< set-cookie: uuid=6fb0a5ae3f794a949101606ab9a317f4; Max-Age=31536000; Domain=.hola.org; Path=/; Expires=Sat, 12 Mar 2022 20:07:09 GMT
< etag: W/"22-qftJtU5fM2WrFerrApPoW4znNag"
< 
* Connection #0 to host client.hola.org left intact
{"blocked":true,"permanent":false}
```

**Comment by rany2** [comment]
Is this what you want?

**Comment by Snawoot** [comment]
@rany2 yes, thanks. I'll just threat all non-2xx responses as faulty.

**Pull request merged**
